### ISSUE TITLE
Provide a requirements file to ensure easy install

### ISSUE THREAD

**Issue by jorisschellekens** [skane88/pdf_utils#1]
Hi there,

I think your project(s) could use a requirements file.

Requirements files ensure that someone using your code will always have the right dependencies installed.

You can auto-generate a requirements file using pip.

Essentially, you are recording all dependencies in your virtual environment in a file. And when someone wants to use your project they can simply ask pip to install everything in the requirements file.

Kind regards,
Joris Schellekens

**Comment by skane88** [comment]
Thanks for looking at my repositories Joris. As you can probably tell I'm a structural engineer first and programmer second so things like requirements.txt files sometimes are an after-thought - it's good to get advice from someone who knows a bit more than I do.
